export const ADD_INDIVIDUAL_MEAL_TO_CART = 'ADD_INDIVIDUAL_MEAL_TO_CART';
export const REMOVE_INDIVIDUAL_MEAL_FROM_CART = 'REMOVE_INDIVIDUAL_MEAL_FROM_CART';

export const ADD_MEAL_PLAN_TO_CART = 'ADD_MEAL_PLAN_TO_CART';
export const REMOVE_MEAL_PLAN_FROM_CART = 'REMOVE_MEAL_PLAN_FROM_CART';

export const SET_INDIVIDUAL_MEALS = 'SET_INDIVIDUAL_MEALS';
export const SET_MEAL_PLANS = 'SET_MEAL_PLANS';

export const RESET_CART = 'RESET_CART';
