const MEALS_ENUM = {
  MEALS: 'MEALS',
  PLUS: 'PLUS',
  BREAKFAST: 'BREAKFAST',
  SNACKS: 'SNACKS',
  DRINKS: 'DRINKS'
}

const BLOGS_ENUM = {
  NUTRITION: 'NUTRITION',
  TRAINING: 'TRAINING',
  TRANSFORMATION: 'TRANSFORMATION',
  WELLBEING: 'WELLBEING',
  WELLNESS: 'WELLNESS',
  NEWS: 'NEWS'
}

module.exports = {
  MEALS_ENUM,
  BLOGS_ENUM
}
